/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AgentMeshEscrowInterface extends Interface {
    getFunction(nameOrSignature: "depositTask" | "refundRemaining" | "releasePayment" | "tasks" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentReleased" | "TaskDeposited" | "TaskRefunded"): EventFragment;

    encodeFunctionData(functionFragment: 'depositTask', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundRemaining', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'releasePayment', values: [BytesLike, BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'depositTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releasePayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace PaymentReleasedEvent {
      export type InputTuple = [taskId: BytesLike, subtaskId: BytesLike, agent: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, subtaskId: string, agent: string, amount: bigint];
      export interface OutputObject {taskId: string, subtaskId: string, agent: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskDepositedEvent {
      export type InputTuple = [taskId: BytesLike, depositor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, depositor: string, amount: bigint];
      export interface OutputObject {taskId: string, depositor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskRefundedEvent {
      export type InputTuple = [taskId: BytesLike, depositor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, depositor: string, amount: bigint];
      export interface OutputObject {taskId: string, depositor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentMeshEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentMeshEscrow;
    waitForDeployment(): Promise<this>;

    interface: AgentMeshEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    depositTask: TypedContractMethod<
      [taskId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refundRemaining: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    releasePayment: TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, agent: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, bigint, boolean] & {depositor: string, totalAmount: bigint, releasedAmount: bigint, active: boolean }],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'depositTask'): TypedContractMethod<
      [taskId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundRemaining'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releasePayment'): TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, agent: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, bigint, boolean] & {depositor: string, totalAmount: bigint, releasedAmount: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'PaymentReleased'): TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
getEvent(key: 'TaskDeposited'): TypedContractEvent<TaskDepositedEvent.InputTuple, TaskDepositedEvent.OutputTuple, TaskDepositedEvent.OutputObject>;
getEvent(key: 'TaskRefunded'): TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;

    filters: {
      
      'PaymentReleased(bytes32,bytes32,address,uint256)': TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
      PaymentReleased: TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
    

      'TaskDeposited(bytes32,address,uint256)': TypedContractEvent<TaskDepositedEvent.InputTuple, TaskDepositedEvent.OutputTuple, TaskDepositedEvent.OutputObject>;
      TaskDeposited: TypedContractEvent<TaskDepositedEvent.InputTuple, TaskDepositedEvent.OutputTuple, TaskDepositedEvent.OutputObject>;
    

      'TaskRefunded(bytes32,address,uint256)': TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
      TaskRefunded: TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
    
    };
  }