/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "agentIds" | "agents" | "deactivateAgent" | "getAgent" | "getAgentsBySkill" | "getAllAgentIds" | "getTotalAgents" | "registerAgent" | "skillToAgents" | "updateCost"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentDeactivated" | "AgentRegistered" | "AgentUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'agentIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agents', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'deactivateAgent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAgent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAgentsBySkill', values: [string]): string;
encodeFunctionData(functionFragment: 'getAllAgentIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalAgents', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [BytesLike, string[], BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'skillToAgents', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateCost', values: [BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'agentIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentsBySkill', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllAgentIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'skillToAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCost', data: BytesLike): Result;
  }

  
    export namespace AgentDeactivatedEvent {
      export type InputTuple = [agentId: BytesLike];
      export type OutputTuple = [agentId: string];
      export interface OutputObject {agentId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRegisteredEvent {
      export type InputTuple = [agentId: BytesLike, owner: AddressLike, skills: string[], costPerTask: BigNumberish];
      export type OutputTuple = [agentId: string, owner: string, skills: string[], costPerTask: bigint];
      export interface OutputObject {agentId: string, owner: string, skills: string[], costPerTask: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentUpdatedEvent {
      export type InputTuple = [agentId: BytesLike, newCost: BigNumberish];
      export type OutputTuple = [agentId: string, newCost: bigint];
      export interface OutputObject {agentId: string, newCost: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agentIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    agents: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, string, boolean, bigint] & {owner: string, costPerTask: bigint, metadata: string, active: boolean, registeredAt: bigint }],
      'view'
    >
    

    
    deactivateAgent: TypedContractMethod<
      [agentId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAgent: TypedContractMethod<
      [agentId: BytesLike, ],
      [[string, string[], bigint, string, boolean, bigint] & {owner: string, skills: string[], costPerTask: bigint, metadata: string, active: boolean, registeredAt: bigint }],
      'view'
    >
    

    
    getAgentsBySkill: TypedContractMethod<
      [skill: string, ],
      [string[]],
      'view'
    >
    

    
    getAllAgentIds: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTotalAgents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [agentId: BytesLike, skills: string[], costPerTask: BigNumberish, metadata: string, ],
      [void],
      'nonpayable'
    >
    

    
    skillToAgents: TypedContractMethod<
      [arg0: string, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    updateCost: TypedContractMethod<
      [agentId: BytesLike, newCost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agentIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, string, boolean, bigint] & {owner: string, costPerTask: bigint, metadata: string, active: boolean, registeredAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'deactivateAgent'): TypedContractMethod<
      [agentId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [agentId: BytesLike, ],
      [[string, string[], bigint, string, boolean, bigint] & {owner: string, skills: string[], costPerTask: bigint, metadata: string, active: boolean, registeredAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentsBySkill'): TypedContractMethod<
      [skill: string, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllAgentIds'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalAgents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [agentId: BytesLike, skills: string[], costPerTask: BigNumberish, metadata: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'skillToAgents'): TypedContractMethod<
      [arg0: string, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateCost'): TypedContractMethod<
      [agentId: BytesLike, newCost: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentDeactivated'): TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'AgentUpdated'): TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentDeactivated(bytes32)': TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
      AgentDeactivated: TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
    

      'AgentRegistered(bytes32,address,string[],uint256)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'AgentUpdated(bytes32,uint256)': TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
      AgentUpdated: TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
    
    };
  }