/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReputationContractInterface extends Interface {
    getFunction(nameOrSignature: "getReputation" | "initializeReputation" | "reputations" | "updateReputation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ReputationInitialized" | "ReputationUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'getReputation', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'initializeReputation', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputations', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateReputation', values: [BytesLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateReputation', data: BytesLike): Result;
  }

  
    export namespace ReputationInitializedEvent {
      export type InputTuple = [agentId: BytesLike, initialScore: BigNumberish];
      export type OutputTuple = [agentId: string, initialScore: bigint];
      export interface OutputObject {agentId: string, initialScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [agentId: BytesLike, success: boolean, newScore: BigNumberish, totalTasks: BigNumberish];
      export type OutputTuple = [agentId: string, success: boolean, newScore: bigint, totalTasks: bigint];
      export interface OutputObject {agentId: string, success: boolean, newScore: bigint, totalTasks: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReputationContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReputationContract;
    waitForDeployment(): Promise<this>;

    interface: ReputationContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getReputation: TypedContractMethod<
      [agentId: BytesLike, ],
      [[bigint, bigint, bigint, bigint] & {score: bigint, totalTasks: bigint, successCount: bigint, successRate: bigint }],
      'view'
    >
    

    
    initializeReputation: TypedContractMethod<
      [agentId: BytesLike, initialScore: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputations: TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, bigint, bigint] & {score: bigint, totalTasks: bigint, successCount: bigint, lastUpdated: bigint }],
      'view'
    >
    

    
    updateReputation: TypedContractMethod<
      [agentId: BytesLike, success: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [agentId: BytesLike, ],
      [[bigint, bigint, bigint, bigint] & {score: bigint, totalTasks: bigint, successCount: bigint, successRate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'initializeReputation'): TypedContractMethod<
      [agentId: BytesLike, initialScore: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputations'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, bigint, bigint] & {score: bigint, totalTasks: bigint, successCount: bigint, lastUpdated: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'updateReputation'): TypedContractMethod<
      [agentId: BytesLike, success: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ReputationInitialized'): TypedContractEvent<ReputationInitializedEvent.InputTuple, ReputationInitializedEvent.OutputTuple, ReputationInitializedEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;

    filters: {
      
      'ReputationInitialized(bytes32,uint256)': TypedContractEvent<ReputationInitializedEvent.InputTuple, ReputationInitializedEvent.OutputTuple, ReputationInitializedEvent.OutputObject>;
      ReputationInitialized: TypedContractEvent<ReputationInitializedEvent.InputTuple, ReputationInitializedEvent.OutputTuple, ReputationInitializedEvent.OutputObject>;
    

      'ReputationUpdated(bytes32,bool,uint256,uint256)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    
    };
  }