/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TaskEscrowInterface extends Interface {
    getFunction(nameOrSignature: "approveWork" | "createTask" | "getProof" | "getTask" | "proofs" | "refundRemaining" | "submitProof" | "tasks"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProofSubmitted" | "TaskCompleted" | "TaskCreated" | "TaskRefunded" | "WorkApproved"): EventFragment;

    encodeFunctionData(functionFragment: 'approveWork', values: [BytesLike, BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTask', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getProof', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getTask', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'proofs', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'refundRemaining', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'submitProof', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'approveWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
  }

  
    export namespace ProofSubmittedEvent {
      export type InputTuple = [taskId: BytesLike, subtaskId: BytesLike, proofHash: BytesLike];
      export type OutputTuple = [taskId: string, subtaskId: string, proofHash: string];
      export interface OutputObject {taskId: string, subtaskId: string, proofHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCompletedEvent {
      export type InputTuple = [taskId: BytesLike, totalReleased: BigNumberish];
      export type OutputTuple = [taskId: string, totalReleased: bigint];
      export interface OutputObject {taskId: string, totalReleased: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCreatedEvent {
      export type InputTuple = [taskId: BytesLike, depositor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, depositor: string, amount: bigint];
      export interface OutputObject {taskId: string, depositor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskRefundedEvent {
      export type InputTuple = [taskId: BytesLike, depositor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, depositor: string, amount: bigint];
      export interface OutputObject {taskId: string, depositor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkApprovedEvent {
      export type InputTuple = [taskId: BytesLike, subtaskId: BytesLike, agent: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, subtaskId: string, agent: string, amount: bigint];
      export interface OutputObject {taskId: string, subtaskId: string, agent: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaskEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaskEscrow;
    waitForDeployment(): Promise<this>;

    interface: TaskEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveWork: TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, agent: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTask: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'payable'
    >
    

    
    getProof: TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, ],
      [[string, boolean, boolean] & {proofHash: string, submitted: boolean, approved: boolean }],
      'view'
    >
    

    
    getTask: TypedContractMethod<
      [taskId: BytesLike, ],
      [[string, bigint, bigint, boolean, bigint] & {depositor: string, totalAmount: bigint, releasedAmount: bigint, active: boolean, createdAt: bigint }],
      'view'
    >
    

    
    proofs: TypedContractMethod<
      [arg0: BytesLike, arg1: BytesLike, ],
      [[string, boolean, boolean, bigint] & {proofHash: string, submitted: boolean, approved: boolean, submittedAt: bigint }],
      'view'
    >
    

    
    refundRemaining: TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitProof: TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, bigint, boolean, bigint] & {depositor: string, totalAmount: bigint, releasedAmount: bigint, active: boolean, createdAt: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveWork'): TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, agent: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTask'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getProof'): TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, ],
      [[string, boolean, boolean] & {proofHash: string, submitted: boolean, approved: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskId: BytesLike, ],
      [[string, bigint, bigint, boolean, bigint] & {depositor: string, totalAmount: bigint, releasedAmount: bigint, active: boolean, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'proofs'): TypedContractMethod<
      [arg0: BytesLike, arg1: BytesLike, ],
      [[string, boolean, boolean, bigint] & {proofHash: string, submitted: boolean, approved: boolean, submittedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'refundRemaining'): TypedContractMethod<
      [taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitProof'): TypedContractMethod<
      [taskId: BytesLike, subtaskId: BytesLike, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, bigint, boolean, bigint] & {depositor: string, totalAmount: bigint, releasedAmount: bigint, active: boolean, createdAt: bigint }],
      'view'
    >;

    getEvent(key: 'ProofSubmitted'): TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
getEvent(key: 'TaskCompleted'): TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
getEvent(key: 'TaskCreated'): TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
getEvent(key: 'TaskRefunded'): TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
getEvent(key: 'WorkApproved'): TypedContractEvent<WorkApprovedEvent.InputTuple, WorkApprovedEvent.OutputTuple, WorkApprovedEvent.OutputObject>;

    filters: {
      
      'ProofSubmitted(bytes32,bytes32,bytes32)': TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
      ProofSubmitted: TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
    

      'TaskCompleted(bytes32,uint256)': TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
      TaskCompleted: TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
    

      'TaskCreated(bytes32,address,uint256)': TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
      TaskCreated: TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
    

      'TaskRefunded(bytes32,address,uint256)': TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
      TaskRefunded: TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
    

      'WorkApproved(bytes32,bytes32,address,uint256)': TypedContractEvent<WorkApprovedEvent.InputTuple, WorkApprovedEvent.OutputTuple, WorkApprovedEvent.OutputObject>;
      WorkApproved: TypedContractEvent<WorkApprovedEvent.InputTuple, WorkApprovedEvent.OutputTuple, WorkApprovedEvent.OutputObject>;
    
    };
  }